### ISSUE TITLE
现在还能部署吗

### ISSUE THREAD

**Issue by Muggles001** [Redlnn/redbot#127]
老哥现在我还能部署这个机器人吗，还是禁止外人部署了，我发现教程文档里的克隆链接已经not found了

**Comment by Muggles001** [comment]
git clone https://github.com/Graiax-Community/redbot.git
就是这个

**Comment by Redlnn** [comment]
不是`Graiax-Community/redbot`，是`Redlnn/redbot`，另外，建议先试试登录上 mirai 再考虑要不要用需要 mirai 的 bot

**Comment by Muggles001** [comment]
谢谢您，我已经测试我能登录上mirai，但是当我进入到文件夹初始化环境时一直报错
root@ser042830427877 redbot]# poetry env use 3.10.4

[tool.poetry] section not found in /root/redbot/pyproject.toml
这是怎么回事

**Comment by Redlnn** [comment]
> 谢谢您，我已经测试我能登录上mirai，但是当我进入到文件夹初始化环境时一直报错 root@ser042830427877 redbot]# poetry env use 3.10.4
> 
> [tool.poetry] section not found in /root/redbot/pyproject.toml 这是怎么回事

不好意思，可能readme没更新，已切换到[pdm](https://pdm.fming.dev/)了，大体用法差不多

**Comment by Muggles001** [comment]
你好谢谢你的帮助，我成功的初始化了，但是为何我填写了配置文件他还要求我填写

2023-05-20 22:03:13.671 | ERROR    | graia.ariadne.util:loguru_exc_callback:76 - Exception:
Traceback (most recent call last):

> File "/root/redbot/main.py", line 67, in <module>
    raise ValueError('在¿填一下配置文件？')

ValueError: 在?¿ 填一下配置文件？

![](https://pic1.imgdb.cn/item/6468d4b2e03e90d8744b1505.jpg)

**Comment by Redlnn** [comment]
在这里
![image](https://github.com/Redlnn/redbot/assets/41742767/e284b8ed-eff7-4cfb-8072-75c7255daaa7)

**Comment by Muggles001** [comment]
还是不行一样的报错
![IMG_0772](https://github.com/Redlnn/redbot/assets/62734960/5c04f338-bf5e-45df-9658-398e48cdb412)

**Comment by Muggles001** [comment]
还是不行一样的报错，而且他还会复原这个文件
![](https://pic1.imgdb.cn/item/6468dfdbe03e90d87458be82.jpg)

**Comment by Redlnn** [comment]
> 还是不行一样的报错，而且他还会复原这个文件
> 
> ![123](https://camo.githubusercontent.com/92c52b60ffdb3e77c6b0d5e25fd049a6580d7847b0a115c5de8b0bfe935ae278/68747470733a2f2f706963312e696d6764622e636e2f6974656d2f3634363864666462653033653930643837343538626538322e6a7067)

握草，圈错了，是`redbot.jsonc`

**Comment by Muggles001** [comment]
我人傻了，还是那个报错
![8B48175C-B356-4CEA-9CCE-374C836D0748](https://github.com/Redlnn/redbot/assets/62734960/6781c895-8f4a-46f8-9e1e-4875225bcbac)

**Comment by Redlnn** [comment]
> 我人傻了，还是那个报错 ![8B48175C-B356-4CEA-9CCE-374C836D0748](https://user-images.githubusercontent.com/62734960/239694851-6781c895-8f4a-46f8-9e1e-4875225bcbac.jpeg)

拜托，用个有高亮的编辑器，你mirai-api-http的账号都不改你怎么连mirai？
![image](https://github.com/Redlnn/redbot/assets/41742767/bf2815bd-f344-4fb5-a42e-4dd28116d997)

**Comment by Muggles001** [comment]
谢谢老哥解答，qq登不上了mi rai，昨天还行，唉

**Comment by Redlnn** [comment]
> 谢谢老哥解答，qq登不上了mi rai，昨天还行，唉

点击链接加入群聊[Graia Framework Community](http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=sASiKT8f0w00sABkgRt_naugUFshPUgR&authKey=MA6TCcCkArHR0OLN6ak4DubHjMXBy8p8qWYpBe3Zmz59D0uXYXNfILG2rcnL%2BJNI&noverify=0&group_code=941310484)来群里问

**Comment by Muggles001** [comment]
大佬你好，我现在能通过扫码登录了，然后我开始重新部署
当我运行redbot，也就是运行pdm run python main.py命令时它报错

```

root@muggles1:~/redbot# pdm run python main.py
Traceback (most recent call last):
  File "/root/redbot/main.py", line 20, in <module>
    from libs import log_level_handler, replace_logger  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redbot/libs/__init__.py", line 10, in <module>
    from libs.config import basic_cfg
  File "/root/redbot/libs/config.py", line 26, in <module>
    @config('redbot')
     ^^^^^^^^^^^^^^^^
  File "/root/redbot/__pypackages__/3.11/lib/kayaku/model.py", line 64, in wrapper
    cls = cast(Type[ConfigModel], dataclass(**kwargs)(cls))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1213, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'libs.config.MAHConfig'> for field miraiApiHttp is not allowed: use default_factory

```

并且并未生成config文件夹，请问我该如何解决，谢谢

**Comment by Redlnn** [comment]
> 

已尝试在 914c757 修复

**Comment by Muggles001** [comment]
貌似依旧不行
 
pdm：2.7.0
python：3.11
ubuntu：20.0.4


‘’’

root@muggles1:~/redbot# pdm run python main.py
Traceback (most recent call last):
  File "/root/redbot/main.py", line 20, in <module>
    from libs import log_level_handler, replace_logger  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redbot/libs/__init__.py", line 10, in <module>
    from libs.config import basic_cfg
  File "/root/redbot/libs/config.py", line 26, in <module>
    @config('redbot')
     ^^^^^^^^^^^^^^^^
  File "/root/redbot/__pypackages__/3.11/lib/kayaku/model.py", line 64, in wrapper
    cls = cast(Type[ConfigModel], dataclass(**kwargs)(cls))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1213, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'libs.config.AdminConfig'> for field admin is not allowed: use default_factory

‘’‘
